export const contactAddressData = [
  {
    id: 1,
    country: "Philippines",
    addressIcon: "assets/location_Address.png",
    address:
      "FBC Asia Pacific Inc,11th Floor One Corporate Center,Julia Vargas Avenue Ortigas Center,San San Antonio,Pasig City 1800,The Philippines",
    phoneIcon: "assets/address.png",
    phone: "+63 917 509 7752 (Globe & Whatsapp)",
    emailIcon: "assets/emailAddress.png",
    email: "info@fbcapac.com",
  },
  {
    id: 2,
    country: "Australia",
    addressIcon: "assets/location_Address.png",
    address:
      "FBC Asia Pacific Inc,Suite 3,1044A Dandenong Rd,Carnegie VIC 3163",
    phoneIcon: "assets/address.png",
    phone: "+1300 228 724",
    emailIcon: "assets/emailAddress.png",
    email: "info@fbcapac.com",
  },
  {
    id: 3,
    country: "Singapore",
    addressIcon: "assets/location_Address.png",
    address: "FBC Asia Pacific Inc,68 Circular Road, #02-01,Singapore 049422",
    phoneIcon: null,
    phone: "",
    emailIcon: null,
    email: "info@fbcapac.com",
  },
  {
    id: 4,
    country: "USA",
    addressIcon: "assets/location_Address.png",
    address: "One Rockefeller Plaza,Floor 10 and 11,new York,10020",
    phoneIcon: null,
    phone: "+1 445 208 7276",
    emailIcon: null,
    email: "info@rananjayaholdings.io",
  },
  {
    id: 5,
    country: "Sri Lanka",
    addressIcon: "assets/location_Address.png",
    address: "1st Floor, No.111 T. B. Jayah Mawatha, Colombo 01000",
    phoneIcon: "",
    phone: "+94 11 514 6699",
    emailIcon: "",
    email: "info@fbcapac.com",
  },
];